version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_assets
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: asset_management
    ports:
      - "5203:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend_assets
    restart: always
    depends_on:
      - postgres
    ports:
      - "3203:3203"
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: admin123
      PGDATABASE: asset_management
      PGPORT: 5432

  employee-assets:
    build: ./Employee-Assets   # 🔁 Corrected casing here
    container_name: employee_assets_ui
    ports:
      - "8006:80"
    restart: always
    depends_on:
      - backend

  hr-assets:
    build: ./HR-Assets   # 🔁 Corrected casing here
    container_name: hr_assets_ui
    ports:
      - "8007:80"
    restart: always
    depends_on:
      - backend


volumes:
  postgres_data:

